SELECT T4.ID FROM (SELECT T2.ID AS FIRST_ID, T2.PARENT_ID AS FIRST_PARENT_ID FROM (SELECT ID, PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL) T, ECOLI_DATA T2
WHERE T2.PARENT_ID = T.ID) T3, ECOLI_DATA T4
WHERE T3.FIRST_ID = T4.PARENT_ID
ORDER BY T4.ID