# -- 코드를 입력하세요

SELECT DATE_FORMAT(OS.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, OS.PRODUCT_ID, OS.USER_ID, OS.SALES_AMOUNT
FROM ONLINE_SALE OS
WHERE YEAR(OS.SALES_DATE) = 2022 AND MONTH(OS.SALES_DATE) = 3 UNION
SELECT DATE_FORMAT(OFS.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, OFS.PRODUCT_ID, NULL AS USER_ID, OFS.SALES_AMOUNT
FROM OFFLINE_SALE OFS
WHERE YEAR(OFS.SALES_DATE) = 2022 AND MONTH(OFS.SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID


# SELECT OS.SALES_DATE, OS.PRODUCT_ID, OS.USER_ID, OS.SALES_AMOUNT
# FROM ONLINE_SALE OS
# WHERE YEAR(OS.SALES_DATE) = 2022 AND MONTH(OS.SALES_DATE) = 3

# SELECT DATE_FORMAT(OFS.SALES_DATE, "%y-%m-%d") AS SALES_DATE, OFS.PRODUCT_ID, NULL AS USER_ID, OFS.SALES_AMOUNT
# FROM OFFLINE_SALE OFS
# WHERE YEAR(OFS.SALES_DATE) = 2022 AND MONTH(OFS.SALES_DATE) = 3