SELECT ID, (CASE 
    WHEN NT = 1 THEN "LOW"
    WHEN NT = 2 THEN "MEDIUM"
    WHEN NT = 3 THEN "HIGH"
    WHEN NT = 4 THEN "CRITICAL"
    END) AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY) AS NT FROM ECOLI_DATA) T 
ORDER BY ID 