-- 코드를 작성해주세요
SELECT COUNT(*) as FISH_COUNT, N.FISH_NAME AS FISH_NAME
FROM FISH_INFO F
INNER JOIN FISH_NAME_INFO N
WHERE F.FISH_TYPE = N.FISH_TYPE
GROUP BY F.FISH_TYPE, N.FISH_NAME
ORDER BY COUNT(*) DESC