-- 코드를 입력하세요
SELECT T.FLAVOR
FROM (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) F
INNER JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF 
    GROUP BY FLAVOR) T
WHERE T.SHIPMENT_ID = F.SHIPMENT_ID
ORDER BY (T.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3