# -- 코드를 입력하세요
SELECT USER_ID, NICKNAME, A.PRICE AS TOTAL_SALES
FROM USED_GOODS_USER, (SELECT WRITER_ID, SUM(PRICE) AS PRICE
FROM USED_GOODS_BOARD
WHERE STATUS = "DONE"
GROUP BY WRITER_ID
HAVING PRICE >= 700000) AS A
WHERE USER_ID = A.WRITER_ID
ORDER BY TOTAL_SALES


# SELECT WRITER_ID, PRICE, STATUS
# FROM USED_GOODS_BOARD
# WHERE STATUS = "DONE"
# ORDER BY WRITER_ID