-- 코드를 작성해주세요
SELECT T.SCORE, T.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM (
    SELECT EMP_NO, YEAR, SUM(SCORE) AS SCORE 
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
)  AS T
INNER JOIN HR_EMPLOYEES AS E
WHERE E.EMP_NO = T.EMP_NO AND T.YEAR = "2022"
ORDER BY T.SCORE DESC
LIMIT 1