-- 코드를 입력하세요
SELECT U.TITLE, U.BOARD_ID, Y.REPLY_ID, Y.WRITER_ID, Y.CONTENTS, DATE_FORMAT(Y.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD U
INNER JOIN USED_GOODS_REPLY Y
WHERE U.BOARD_ID = Y.BOARD_ID 
AND YEAR(U.CREATED_DATE) = 2022
AND MONTH(U.CREATED_DATE) = 10
ORDER BY Y.CREATED_DATE, U.TITLE