# -- 코드를 입력하세요
# SELECT CONCAT("/home/grep/src/", F.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH FROM
# (SELECT MAX(VIEWS) AS "VIEWS", BOARD_ID FROM USED_GOODS_BOARD) B, USED_GOODS_FILE F
# WHERE B.BOARD_ID = F.BOARD_ID
# ORDER BY F.FILE_ID DESC

# SELECT * FROM USED_GOODS_FILE

SELECT
    CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS FILE
LEFT JOIN USED_GOODS_BOARD AS B
ON FILE.BOARD_ID = B.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC