# -- 코드를 입력하세요
# SELECT B.CATEGORY, S.SALES AS TOTAL_SALES, S.SALES_DATE
# FROM BOOK B, BOOK_SALES S
# WHERE B.BOOK_ID = S.BOOK_ID 
# AND YEAR(S.SALES_DATE) = 2022
# AND MONTH(S.SALES_DATE) = 1
# GROUP BY B.CATEGORY
# ORDER BY B.CATEGORY

# SELECT *
# FROM BOOK B, BOOK_SALES S
# WHERE B.BOOK_ID = S.BOOK_ID
# GROUP BY S.SALES

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S, BOOK B
WHERE YEAR(S.SALES_DATE) = 2022
AND MONTH(S.SALES_DATE) = 1
AND B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY